### ISSUE TITLE
Can`t run cygger

### ISSUE THREAD

**Issue by Mynken** [RamirezAlex/cygger#1]
Hi,
I want to launch cygger:
`cygger test\swagger.yml -o test --baseURL http://localhost:5000/swagger`.

And getting this error:

> node:14576) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at endpoint.responses.map (C:\Users\Waldes\AppData\Roaming\npm\node_modules\cygger\lib\index.js:103:16)
    at Array.map (<anonymous>)
    at parsed.endpoints.map (C:\Users\Waldes\AppData\Roaming\npm\node_modules\cygger\lib\index.js:99:24)
    at Array.map (<anonymous>)
    at generate (C:\Users\Waldes\AppData\Roaming\npm\node_modules\cygger\lib\index.js:98:20)
    at main (C:\Users\Waldes\AppData\Roaming\npm\node_modules\cygger\index.js:27:29)
(node:14576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Mynken** [comment]
`
swagger: '2.0'
info:
  version: v1
  title: starter API
paths:
  "/api/Account/users/me":
    get:
      tags:
      - Account
      operationId: GetCurrentUser
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
    put:
      tags:
      - Account
      operationId: UpdateCurrentUser
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: user
        in: body
        required: false
        schema:
          "$ref": "#/definitions/UserEditViewModel"
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
    patch:
      tags:
      - Account
      operationId: UpdateCurrentUser
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: patch
        in: body
        required: false
        schema:
          uniqueItems: false
          type: array
          items:
            "$ref": "#/definitions/Operation"
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
  "/api/Account/users/{id}":
    get:
      tags:
      - Account
      operationId: GetUserById
      consumes: []
      produces: []
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
    put:
      tags:
      - Account
      operationId: UpdateUser
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: user
        in: body
        required: false
        schema:
          "$ref": "#/definitions/UserEditViewModel"
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
    delete:
      tags:
      - Account
      operationId: DeleteUser
      consumes: []
      produces: []
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
    patch:
      tags:
      - Account
      operationId: UpdateUser
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: patch
        in: body
        required: false
        schema:
          uniqueItems: false
          type: array
          items:
            "$ref": "#/definitions/Operation"
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
  "/api/Account/users/username/{userName}":
    get:
      tags:
      - Account
      operationId: GetUserByUserName
      consumes: []
      produces: []
      parameters:
      - name: userName
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
  "/api/Account/users":
    get:
      tags:
      - Account
      operationId: GetUsers
      consumes: []
      produces:
      - text/plain
      - application/json
      - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              "$ref": "#/definitions/UserViewModel"
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
    post:
      tags:
      - Account
      operationId: Register
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: user
        in: body
        required: false
        schema:
          "$ref": "#/definitions/UserEditViewModel"
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
  "/api/Account/users/{pageNumber}/{pageSize}":
    get:
      tags:
      - Account
      operationId: GetUsers
      consumes: []
      produces: []
      parameters:
      - name: pageNumber
        in: path
        required: true
        type: integer
        format: int32
      - name: pageSize
        in: path
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
  "/api/Account/users/unblock/{id}":
    put:
      tags:
      - Account
      operationId: UnblockUser
      consumes: []
      produces: []
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
  "/api/Account/users/me/preferences":
    get:
      tags:
      - Account
      operationId: UserPreferences
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
    put:
      tags:
      - Account
      operationId: UserPreferences
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: data
        in: body
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
  "/api/Account/roles/{id}":
    get:
      tags:
      - Account
      operationId: GetRoleById
      consumes: []
      produces: []
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
    put:
      tags:
      - Account
      operationId: UpdateRole
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: role
        in: body
        required: false
        schema:
          "$ref": "#/definitions/RoleViewModel"
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
    delete:
      tags:
      - Account
      operationId: DeleteRole
      consumes: []
      produces: []
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
  "/api/Account/roles/name/{name}":
    get:
      tags:
      - Account
      operationId: GetRoleByName
      consumes: []
      produces: []
      parameters:
      - name: name
        in: path
        required: true
        type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
  "/api/Account/roles":
    get:
      tags:
      - Account
      operationId: GetRoles
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
    post:
      tags:
      - Account
      operationId: CreateRole
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: role
        in: body
        required: false
        schema:
          "$ref": "#/definitions/RoleViewModel"
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
  "/api/Account/roles/{pageNumber}/{pageSize}":
    get:
      tags:
      - Account
      operationId: GetRoles
      consumes: []
      produces: []
      parameters:
      - name: pageNumber
        in: path
        required: true
        type: integer
        format: int32
      - name: pageSize
        in: path
        required: true
        type: integer
        format: int32
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
  "/api/Account/permissions":
    get:
      tags:
      - Account
      operationId: GetAllPermissions
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      security:
      - oauth2:
        - starter_api
  "/api/Values":
    get:
      tags:
      - Values
      operationId: GetDictionaryById
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
definitions:
  UserEditViewModel:
    required:
    - userName
    - email
    type: object
    properties:
      currentPassword:
        type: string
      newPassword:
        minLength: 6
        type: string
      roles:
        uniqueItems: false
        type: array
        items:
          type: string
      id:
        type: string
      userName:
        maxLength: 200
        minLength: 2
        type: string
      fullName:
        type: string
      email:
        maxLength: 200
        minLength: 0
        type: string
      jobTitle:
        type: string
      phoneNumber:
        type: string
      configuration:
        type: string
      isEnabled:
        type: boolean
  Operation:
    type: object
    properties:
      value:
        type: object
      path:
        type: string
      op:
        type: string
      from:
        type: string
  UserViewModel:
    required:
    - userName
    - email
    type: object
    properties:
      isLockedOut:
        type: boolean
      roles:
        uniqueItems: false
        type: array
        items:
          type: string
      id:
        type: string
      userName:
        maxLength: 200
        minLength: 2
        type: string
      fullName:
        type: string
      email:
        maxLength: 200
        minLength: 0
        type: string
      jobTitle:
        type: string
      phoneNumber:
        type: string
      configuration:
        type: string
      isEnabled:
        type: boolean
  RoleViewModel:
    required:
    - name
    type: object
    properties:
      id:
        type: string
      name:
        maxLength: 200
        minLength: 2
        type: string
      description:
        type: string
      usersCount:
        format: int32
        type: integer
      permissions:
        uniqueItems: false
        type: array
        items:
          "$ref": "#/definitions/PermissionViewModel"
  PermissionViewModel:
    type: object
    properties:
      name:
        type: string
      value:
        type: string
      groupName:
        type: string
      description:
        type: string
securityDefinitions:
  oauth2:
    flow: password
    tokenUrl: http://localhost:5000/connect/token
    scopes:
      starter_api: starter API
    type: oauth2
`

Yaml file

**Comment by Mynken** [comment]
@RamirezAlex tnx, today will try your fix. 
If it will work I will also check yaml from one more project, where could be potential problems.
Also:
Is there opportunity to use cygger with swagger.json or swagger.yaml(not .yml)?
Because default export for swagger is json(or maybe I should look into swagger documentaion).
Thanks,
Vlad

**Comment by RamirezAlex** [comment]
Thanks @Mynken! 
Yes, cygger supports `.json` `.yml` and `.yaml` files.
I will write better documentation when I have a chance.
